name: Boot Windows

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Setup Windows
        run: |
             mkdir windows && cd windows
             wget https://raw.githubusercontent.com/mjuned47/windows-qemu/refs/heads/master/compose.yml
             
      - name: Setup NGROK
        run: |
             wget https://raw.githubusercontent.com/mjuned47/windows-qemu/refs/heads/master/ngrok.yml -O ~/.config/ngrok/ngrok.yml
             ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
             
      - name: Start Windows
        run: |
             docker compose up && ngrok start --all
